In [17]:
import pandas as pd

In [18]:
df=pd.read_csv("/content/drive/MyDrive/EXCEL/train.csv")

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [20]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [21]:
df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [22]:
df=df.dropna()

In [23]:
df.isna().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [24]:
x=df.drop('label',axis=1)

In [25]:
y=df['label']

In [26]:
y.shape

(18285,)

In [27]:
import tensorflow as tf


In [28]:
tf.__version__

'2.12.0'

In [29]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [30]:
voc_size=5000

In [31]:
messages=x.copy()

In [32]:
messages.reset_index(inplace=True)

In [33]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [34]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',messages['title'][i]).lower().split()
  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)


Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [35]:
ohr=[one_hot(words,voc_size) for words in corpus]
ohr


[[2160, 1014, 4989, 103, 1066, 2247, 3109, 1343, 2344, 3181],
 [2863, 3993, 2983, 2231, 4533, 733, 1990],
 [1410, 3482, 149, 4891],
 [4998, 2292, 2436, 1316, 4058, 3293],
 [2538, 4533, 4549, 4696, 2353, 3316, 4533, 895, 2335, 1174],
 [1011,
  91,
  3472,
  4521,
  1711,
  1961,
  4589,
  3886,
  1527,
  4541,
  1985,
  3046,
  1330,
  485,
  1990],
 [1294, 2369, 3006, 1034, 528, 2845, 1074, 1452, 3730, 2543, 3191],
 [1876, 2397, 1658, 4829, 761, 2394, 1961, 1592, 3730, 2543, 3191],
 [4592, 4391, 1042, 2164, 101, 1399, 4115, 4135, 1961, 77],
 [2312, 69, 2680, 3305, 4951, 2911, 2108, 3584],
 [1982, 300, 4936, 3266, 4896, 139, 4951, 4940, 1099, 594, 835],
 [1316, 4244, 1066, 1399, 1961, 761],
 [3582, 3730, 4438, 3178, 2708, 3235, 990, 1065, 3093],
 [2787, 4248, 3326, 2292, 3197, 3867, 3189, 3730, 2543, 3191],
 [740, 1286, 3054, 1758, 2067, 3730, 2543, 3191],
 [471, 2434, 3356, 4402, 2267, 2920, 377, 3093, 2180, 4343],
 [4174, 4888, 3993],
 [4757, 1931, 4935, 4082, 1961, 1241, 2616, 1990],

In [36]:
sent_len=20
embd_doc=pad_sequences(ohr,padding='pre',maxlen=sent_len)
embd_doc

array([[   0,    0,    0, ..., 1343, 2344, 3181],
       [   0,    0,    0, ..., 4533,  733, 1990],
       [   0,    0,    0, ..., 3482,  149, 4891],
       ...,
       [   0,    0,    0, ..., 3730, 2543, 3191],
       [   0,    0,    0, ..., 3451, 4352, 4228],
       [   0,    0,    0, ..., 2628, 3519, 2604]], dtype=int32)

In [37]:
embd_doc[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2160,
       1014, 4989,  103, 1066, 2247, 3109, 1343, 2344, 3181], dtype=int32)

In [38]:
sent_len=20
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [39]:
import numpy as np
x_final=np.array(embd_doc)
y_final=np.array(y)

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.2,random_state=0)

In [41]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
229/229 [==============================] - 13s 43ms/step - loss: 0.3031 - accuracy: 0.8580 - val_loss: 0.1875 - val_accuracy: 0.9207
Epoch 2/10
229/229 [==============================] - 10s 42ms/step - loss: 0.1400 - accuracy: 0.9455 - val_loss: 0.1896 - val_accuracy: 0.9248
Epoch 3/10
229/229 [==============================] - 11s 50ms/step - loss: 0.1035 - accuracy: 0.9621 - val_loss: 0.1955 - val_accuracy: 0.9251
Epoch 4/10
229/229 [==============================] - 10s 43ms/step - loss: 0.0771 - accuracy: 0.9726 - val_loss: 0.2135 - val_accuracy: 0.9196
Epoch 5/10
229/229 [==============================] - 9s 39ms/step - loss: 0.0542 - accuracy: 0.9813 - val_loss: 0.2804 - val_accuracy: 0.9177
Epoch 6/10
229/229 [==============================] - 11s 46ms/step - loss: 0.0383 - accuracy: 0.9878 - val_loss: 0.2571 - val_accuracy: 0.9133
Epoch 7/10
229/229 [==============================] - 10s 42ms/step - loss: 0.0269 - accuracy: 0.9912 - val_loss: 0.3732 - val_accuracy: 

In [42]:
y_pred = (model.predict(x_test) > 0.5).astype("int32")


115/115 [==============================] - 1s 7ms/step


In [51]:
y_pred.shape

(3657, 1)

In [44]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1885,  155],
       [ 157, 1460]])

In [45]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9146841673502871

In [46]:
import re
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
voc_size=5000
test_review=re.sub('[^a-zA-Z]',' ',"india's prime minister kills the president of us").lower().split()
test_review=[ps.stem(word) for word in test_review if not word in stopwords.words('english')]
test_review=' '.join(test_review)
ohr=[one_hot(words,voc_size) for words in test_review]
ohr

[[4039],
 [2645],
 [4024],
 [4039],
 [2333],
 [],
 [2293],
 [3403],
 [4039],
 [1511],
 [3962],
 [],
 [1511],
 [4039],
 [2645],
 [4039],
 [4228],
 [2059],
 [],
 [2857],
 [4039],
 [1090],
 [1090],
 [],
 [2293],
 [3403],
 [3962],
 [4228],
 [4039],
 [4024],
 [],
 [2280],
 [4228]]

In [47]:
embd_doc=pad_sequences(ohr,padding='pre',maxlen=20)
embd_doc

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 4039],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 2645],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 4024],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 4039],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 2333],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0, 2293],
       [   0,    0,    0,    0,    0,    

In [52]:
import numpy as np
x_test_review=np.array(embd_doc)
ypred=(model.predict(x_test_review) > 0.5).astype("int32")

2/2 [==============================] - 0s 8ms/step


In [54]:
ypred.shape

(33, 1)

In [55]:
ypred

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=int32)